### ISSUE TITLE
add sugar function(s) that receives domains and returns app

### ISSUE THREAD

**Issue by ahdinosaur** [ahdinosaur/inu#11]
it'd be sweet for `inu` to include sugar functions that receives [model (domain) objects like in `choo`](https://github.com/yoshuawuyts/choo#models) ([todomvc example](https://github.com/shuhei/todomvc-choo/blob/master/model.js)) and returns composed [`inu` app objects](https://github.com/ahdinosaur/inu#usage).

even better if we couple this with [`bulk-require`](https://www.npmjs.com/package/bulk-require) (and [`bulkify`](https://www.npmjs.com/package/bulkify)), so you could use a single call to compose all the models (domains).

/cc @yoshuawuyts

**Comment by yoshuawuyts** [comment]
ooh, `bulkify` and `bulk-require` are interesting! not quite sure what you mean by "sugar methods", but it seems like you're on track to something neat

**Comment by ahdinosaur** [comment]
done with [`inux`](https://github.com/ahdinosaur/inux) :8ball:
