### ISSUE TITLE
test stream filter behaviors

### ISSUE THREAD

**Issue by ahdinosaur** [ahdinosaur/inu#8]
@pietgeursen, if we wanna test all the things... here's some moar i realized:

- [x] [`models()` stream won't receive a new item when it's the same as the last item](https://github.com/ahdinosaur/inu/blob/master/start.js#L39)
- [x] [`views()` stream won't receive `null` or `undefined` views](https://github.com/ahdinosaur/inu/blob/master/start.js#L49)
- [x] [`effects()` stream won't receive `null` or `undefined` effects](https://github.com/ahdinosaur/inu/blob/master/start.js#L59)
- [x] [`effectActionStreams()` won't receive `null` or `undefined` streams returned from `run`](https://github.com/ahdinosaur/inu/blob/master/start.js#L69)

but i'm also quite happy that we have any tests at all. :blush:

**Comment by pietgeursen** [comment]
Yep, seems good to test. Will add them I reckon.
